# Generated by Django 3.1.3 on 2021-01-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_branch_storeincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveMountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain_name', models.CharField(max_length=200)),
                ('mountain_high', models.PositiveIntegerField()),
            ],
        ),
    ]
